FROM ubuntu:latest

RUN apt-get update
RUN apt-get install -y curl bzip2 python3 python3-pip graphviz
RUN pip3 install pydot astunparse networkx matplotlib graphviz
RUN pip3 install python-igraph plotly==5.13.1 seaborn
RUN pip3 install pdflatex
RUN pip3 install generate-ast-aapoliakova==0.0.2
RUN pip3 install -U kaleido
RUN apt-get -y --no-install-recommends install texlive-latex-base texlive-fonts-recommended texlive-fonts-extra texlive-latex-extra

ADD . .
